[package]
name = "asn_mining"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "asn_mining"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
bgpkit-parser = "0.10.11"
csv = "1.3.1"